package com.MavenProjects;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

public class Adactin_Maven {

	public static void main(String[] args) throws AWTException, InterruptedException {
		
		WebDriverManager.chromedriver().setup();
		ChromeDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://www.google.co.in/");
		WebElement findElement = driver.findElement(By.name("q"));
		findElement.sendKeys("adactin hotel");
		Robot r = new Robot();
		r.keyPress(KeyEvent.VK_ENTER);
		r.keyRelease(KeyEvent.VK_ENTER);
		WebElement findElement2 = driver.findElement(By.xpath("//h3[text()='Adactin.com - Hotel Reservation System']"));
		findElement2.click();
		WebElement findElement3 = driver.findElement(By.id("username"));
		findElement3.sendKeys("sathishhicet");
		Thread.sleep(500);
		WebElement findElement4 = driver.findElement(By.id("password"));
		findElement4.sendKeys("hicet.322");
		Thread.sleep(500);
		WebElement findElement5 = driver.findElement(By.id("login"));
		findElement5.click();
		WebElement findElement7 = driver.findElement(By.id("location"));
		Select a = new Select(findElement7);
		a.selectByValue("London");
		Thread.sleep(500);
		WebElement findElement8 = driver.findElement(By.id("hotels"));
		Select b = new Select(findElement8);
		b.selectByValue("Hotel Sunshine");
		Thread.sleep(500);
		WebElement findElement9 = driver.findElement(By.id("room_type"));
		Select c = new Select(findElement9);
		c.selectByValue("Double");
		Thread.sleep(500);
		WebElement findElement10 = driver.findElement(By.id("room_nos"));
		Select d = new Select(findElement10);
		d.selectByValue("4");
		Thread.sleep(500);
		WebElement findElement11 = driver.findElement(By.id("datepick_in"));
		findElement11.clear();
		findElement11.sendKeys("13/11/2022");
		Thread.sleep(500);
		WebElement findElement6 = driver.findElement(By.id("datepick_out"));
		findElement6.clear();
		findElement6.sendKeys("15/11/2022");
		Thread.sleep(500);
		WebElement findElement12 = driver.findElement(By.id("adult_room"));
		Select e = new Select(findElement12);
		e.selectByValue("3");
		Thread.sleep(500);
		WebElement findElement13 = driver.findElement(By.id("child_room"));
		Select f = new Select(findElement13);
		f.selectByValue("2");
		Thread.sleep(500);
		WebElement findElement14 = driver.findElement(By.id("Submit"));
		findElement14.click();
		Thread.sleep(500);
		WebElement findElement15 = driver.findElement(By.id("radiobutton_0"));
		findElement15.click();
		Thread.sleep(500);
		driver.findElement(By.id("continue")).click();
		Thread.sleep(500);
		JavascriptExecutor g = (JavascriptExecutor) driver;
		g.executeScript("window.scroll(0,2000)");
		Thread.sleep(500);
		WebElement findElement18 = driver.findElement(By.id("first_name"));
		findElement18.sendKeys("Thar");
		Thread.sleep(500);
		WebElement findElement19 = driver.findElement(By.id("last_name"));
		findElement19.sendKeys("Worx");
		Thread.sleep(500);
		WebElement findElement20 = driver.findElement(By.id("address"));
		findElement20.sendKeys("Attur Salem district Pin-636113");
		Thread.sleep(500);
		WebElement findElement21 = driver.findElement(By.id("cc_num"));
		findElement21.sendKeys("1234567890123456");
		Thread.sleep(500);
		WebElement findElement22 = driver.findElement(By.id("cc_type"));
		Select h = new Select(findElement22);
		h.selectByValue("MAST");
		Thread.sleep(500);
		WebElement findElement23 = driver.findElement(By.id("cc_exp_month"));
		Select i = new Select(findElement23);
		i.selectByValue("2");
		Thread.sleep(500);
		WebElement findElement24 = driver.findElement(By.id("cc_exp_year"));
		Select j = new Select(findElement24);
		j.selectByValue("2022");
		Thread.sleep(500);
		WebElement findElement25 = driver.findElement(By.name("cc_cvv"));
		findElement25.sendKeys("654");
		g.executeScript("window.scroll(0,2000)");
		WebElement findElement17 = driver.findElement(By.id("book_now")); // book now button
		findElement17.click();
		Thread.sleep(500);

		WebDriverWait wait = new WebDriverWait(driver, 30);
		WebElement findElement30 = wait.until(ExpectedConditions.elementToBeClickable(By.id("search_hotel")));
		findElement30.click();
		Thread.sleep(500);

		WebElement findElement32 = driver.findElement(By.id("location"));
		Select k = new Select(findElement32);
		k.selectByValue("Sydney");
		WebElement findElement33 = driver.findElement(By.id("hotels"));
		Select l = new Select(findElement33);
		l.selectByValue("Hotel Creek");
		Thread.sleep(500);
		WebElement findElement34 = driver.findElement(By.id("room_type"));
		Select m = new Select(findElement34);
		m.selectByValue("Deluxe");
		Thread.sleep(500);
		WebElement findElement35 = driver.findElement(By.id("room_nos"));
		Select n = new Select(findElement35);
		n.selectByValue("3");
		Thread.sleep(500);
		WebElement findElement36 = driver.findElement(By.id("datepick_in"));
		findElement36.clear();
		findElement36.sendKeys("25/11/2022");
		Thread.sleep(500);
		WebElement findElement37 = driver.findElement(By.id("datepick_out"));
		findElement37.clear();
		findElement37.sendKeys("30/11/2022");
		Thread.sleep(500);
		WebElement findElement38 = driver.findElement(By.id("adult_room"));
		Select o = new Select(findElement38);
		o.selectByValue("2");
		Thread.sleep(500);
		WebElement findElement39 = driver.findElement(By.id("child_room"));
		Select p = new Select(findElement39);
		p.selectByValue("3");
		Thread.sleep(500);
		driver.findElement(By.id("Submit")).click();
		Thread.sleep(500);
		driver.findElement(By.id("radiobutton_0")).click();
		Thread.sleep(500);
		driver.findElement(By.id("continue")).click();
		Thread.sleep(500);
		g.executeScript("window.scroll(0,2000)");
		Thread.sleep(500);
		driver.findElement(By.id("first_name")).sendKeys("Gokul");
		Thread.sleep(500);
		driver.findElement(By.id("last_name")).sendKeys("Kannan");
		Thread.sleep(500);
		driver.findElement(By.id("address")).sendKeys("Hasthampatti Salem Pin-636008");
		Thread.sleep(500);
		driver.findElement(By.id("cc_num")).sendKeys("0987654321123456");
		Thread.sleep(500);
		WebElement findElement40 = driver.findElement(By.id("cc_type"));
		Select q = new Select(findElement40);
		q.selectByValue("VISA");
		Thread.sleep(500);
		WebElement findElement41 = driver.findElement(By.id("cc_exp_month"));
		Select s = new Select(findElement41);
		s.selectByValue("4");
		Thread.sleep(500);
		WebElement findElement42 = driver.findElement(By.id("cc_exp_year"));
		Select t = new Select(findElement42);
		t.selectByValue("2022");
		Thread.sleep(500);
		driver.findElement(By.name("cc_cvv")).sendKeys("123");
		Thread.sleep(500);
		driver.findElement(By.id("book_now")).click();
		Thread.sleep(500);
		g.executeScript("window.scroll(0,2000)");
		Thread.sleep(500);
//		WebElement findElement31 = driver.findElement(By.id("my_itinerary"));
//		findElement31.click();

		WebElement findElement31 = wait.until(ExpectedConditions.elementToBeClickable(By.id("my_itinerary")));
		findElement31.click();
		Thread.sleep(500);

		WebElement findElement26 = driver.findElement(By.xpath("//a[text()='Booked Itinerary']"));
		findElement26.click();
		Thread.sleep(500);
		driver.findElement(By.name("ids[]")).click();
		Thread.sleep(500);
		driver.findElement(By.name("cancelall")).click();
		Alert alert = driver.switchTo().alert();
		alert.accept();
		Thread.sleep(500);
		driver.findElement(By.name("ids[]")).click();
		Thread.sleep(500);
		driver.findElement(By.name("cancelall")).click();
		Alert alert1 = driver.switchTo().alert();
		alert1.accept();
		Thread.sleep(500);
		WebElement findElement29 = driver.findElement(By.id("logout"));
		findElement29.click();
		Thread.sleep(500);
		driver.close();
	}

	}

